<?php
// config.php - generated by setup.php. You can edit carefully if needed.
return [
    'db' => [
        'host' => 'localhost',
        'user' => 'cyberros_aiuser',
        'pass' => 'Admin4gpt*',
        'name' => 'cyberros_bizcashapp',
    ],
    'app' => [
        'version' => '1.2',
        'currency' => 'NGN',
        'country' => 'Nigeria',
        'tax_enabled' => false,
        'tax_rate' => 7.5, // 7.5% VAT default for Nigeria
        'admin_user' => [
            'username' => 'admin',
            // setup.php will overwrite this with a secure hash
            'password_hash' => null,
            'role' => 'admin'
        ],
    ],
];
?>